---
services:
  modbus-sim:
    build: ./modbus-sim
    container_name: modbus-sim
    networks:
      - ev-network
  gateway-core:
    build: ./gateway-core
    container_name: gateway-core
    ports:
      - "8000:8000"
    volumes:
      - gateway-data:/app
    networks:
      - ev-network
    depends_on:
      - modbus-sim

  edge-client:
    build: ./edge-client
    container_name: edge-client
    networks:
      - ev-network
networks:
  ev-network:
volumes:
  gateway-data:
